site_name: langbench
site_url: https://micvitc.github.io/langbench/
nav:
    - Home: index.md
    - How to use: tutorial.md
    - Metrics: metrics.md
    - Benchmarks: benchmarks.md
repo_url: https://github.com/micvitc/langbench/
repo_name: micvitc/langbench

theme:
    name: material
    features:
        - content.code.copy
        - content.code.select
    palette:
        primary: black
        accent: indigo
    version:
        provider: pip
        package: langbench
plugins:
    - mkdocstrings
    - social:
        enabled: !ENV [CI, false]
        cards: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences